import { Country } from './interfaces';

export const countries: Country[] = [
  {
    country: 'Tunisia',
    cities: [
      'Tunis',
      'Kasserine',
      'Sfax',
      'Sousse',
      'Kairouan',
      'Gabès',
      'Bizerte',
      'Ariana',
      'Gafsa',
      'Monastir',
      'Ben Arous',
    ],
  },
  {
    country: 'United States',
    cities: [
      'Adak',
      'Pago Pago',
      'Honolulu',
      'Hilo',
      'Anchorage',
      'Fairbanks',
      'Sitka',
      'Juneau',
      'Adamstown',
      'Portland',
      'San Francisco',
      'Jacksonville',
      'Charlotte',
      'Miami',
      'Pittsburgh',
      'Buffalo',
      'Raleigh',
      'Jamestown',
      'Hagåtña',
      'Dededo',
      'Saipan',
      'St. Louis',
      'New York City',
    ],
  },
  {
    country: 'Canada',
    cities: [
      'Whitehorse',
      'Vancouver',
      'Yellowknife',
      'Calgary',
      'Edmonton',
      'Saskatoon',
      'Regina',
      'Winnipeg',
      'Toronto',
      'Ottawa',
      'Montreal',
      'Iqaluit',
      'Fredericton',
      'Charlottetown',
      "St. John's",
      'Quebec City',
      'City of Halifax',
    ],
  },
  {
    country: 'Mexico',
    cities: [
      'Tijuana',
      'Mexicali',
      'Chihuahua',
      'Durango',
      'Zapopan',
      'Guadalajara',
      'Monterrey',
      'Mexico City',
      'Puebla',
      'Veracruz',
      'Mérida',
    ],
  },
  {
    country: 'Chile',
    cities: [
      'Hanga Roa',
      'Valdivia',
      'Concepción',
      'Valparaíso',
      'La Serena',
      'Punta Arenas',
      'Santiago',
      'Antofagasta',
      'Iquique',
      'Calama',
      'Puerto Williams',
    ],
  },
  {
    country: 'Malaysia',
    cities: [
      'George Town',
      'Ipoh',
      'Kuala Lumpur',
      'Kota Bharu',
      'Johor Bahru',
      'Kuching',
      'Miri',
      'Kota Kinabalu',
      'Alor Star',
      'Malacca Town',
    ],
  },
  {
    country: 'Brazil',
    cities: [
      'Rio Branco',
      'Porto Velho',
      'Boa Vista',
      'Manaus',
      'Cuiabá',
      'Campo Grande',
      'Chuí',
      'Pelotas',
      'Porto Alegre',
      'Macapá',
      'Curitiba',
      'Belém',
      'Brasília',
      'Campinas',
      'São Paulo',
      'Vitória',
      'Ilhéus',
      'Fortaleza',
      'Maceió',
      'Recife',
      'Praia',
      'Porto',
      'São Tomé',
      'Bern',
      'São José dos Campos',
      'Rio de Janeiro',
    ],
  },
  {
    country: 'Argentina',
    cities: [
      'Mendoza',
      'Ushuaia',
      'Córdoba',
      'Bahía Blanca',
      'Rosario',
      'Buenos Aires',
      'San Carlos de Bariloche',
      'Ciudad del Este',
    ],
  },
  {
    country: 'Italy',
    cities: ['Assis', 'Turin', 'Milan', 'Rome', 'Naples'],
  },
  {
    country: 'Portugal',
    cities: ['Ponta Delgada', 'Lisbon', 'Horta (Azores)', 'Angra do Heroísmo'],
  },
  {
    country: 'Morocco',
    cities: ['Casablanca', 'Rabat', 'Marrakech'],
  },
  {
    country: 'Spain',
    cities: [
      'Seville',
      'Málaga',
      'Madrid',
      'Bilbao',
      'Valencia',
      'Ibiza',
      'Barcelona',
      'Palma',
      'Santa Cruz de Tenerife',
      'Las Palmas de Gran Canaria',
    ],
  },
  {
    country: 'United Kingdom',
    cities: [
      'Belfast',
      'Glasgow',
      'Cardiff',
      'Edinburgh',
      'Liverpool',
      'Manchester',
      'Aberdeen',
      'Birmingham',
      'Leeds',
      'London',
      'Greenwich',
      'Newcastle',
    ],
  },
  {
    country: 'Australia',
    cities: [
      'Douglas',
      'Mandurah',
      'Perth',
      'Port Hedland',
      'Darwin',
      'Adelaide',
      'Geelong',
      'Melbourne',
      'Cairns',
      'Townsville',
      'Hobart',
      'Canberra',
      'Rockhampton',
      'Wollongong',
      'Sydney',
      'Brisbane',
      'Gold Coast',
    ],
  },
  {
    country: 'France',
    cities: [
      'Nantes',
      'Toulouse',
      'Paris',
      'Lyon',
      'Marseille',
      'Cannes',
      'Nice',
      'Strasbourg',
    ],
  },
  {
    country: 'Nigeria',
    cities: ['Lagos', 'Ibadan', 'Abuja', 'Enugu', 'Kano'],
  },
  {
    country: 'Netherlands',
    cities: ['The Hague', 'Rotterdam', 'Amsterdam'],
  },
  {
    country: 'Germany',
    cities: [
      'Düsseldorf',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Hanover',
      'Hamburg',
      'Munich',
      'Leipzig',
      'Berlin',
      'Dresden',
    ],
  },
  {
    country: 'South Africa',
    cities: [
      'Cape Town',
      'Port Elizabeth',
      'Bloemfontein',
      'Johannesburg',
      'Pretoria',
      'Durban',
    ],
  },
  {
    country: 'Poland',
    cities: ['Kraków', 'Warsaw', 'Gdańsk'],
  },
  {
    country: 'Russia',
    cities: [
      'Kaliningrad',
      'Saint Petersburg',
      'Murmansk',
      'Moscow',
      'Samara',
      'Perm',
      'Yekaterinburg',
      'Omsk',
      'Novosibirsk',
      'Norilsk',
      'Bratsk',
      'Yakutsk',
      'Vladivostok',
      'Magadan',
      'Nizhny Novgorod',
      'Petropavlovsk-Kamchatsky',
    ],
  },
  {
    country: 'Greece',
    cities: ['Athens', 'Thessaloniki'],
  },
];
